import Head from "next/head";
import styles from "@/styles/Home.module.css";
import InputWrapper from "components/input-wrapper";
import List from "components/list";
import Footer from "components/footer";
import { getToDoListStore, StoreContext } from "@/store";
import { LoadingOutlined } from "@ant-design/icons";
import Tools from "@/components/tools";

function Home() {
  const store = getToDoListStore();
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreContext.Provider value={store}>
        <main className={styles.main}>
          {store.loading ? (
            <LoadingOutlined style={{ fontSize: 24 }} spin />
          ) : (
            <>
              <Tools />
              <InputWrapper />
              <List />
              <Footer />
            </>
          )}
        </main>
      </StoreContext.Provider>
    </>
  );
}

export default Home;
