import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { InputWrapper } from "components/input-wrapper";
import { List } from "components/list";
import { Footer } from "components/footer";
import { getToDoListStore, StoreContext } from "@/store";
import { useMount } from "ahooks";

function Home() {
  const store = getToDoListStore();

  useMount(() => {
    store.init();
  });

  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreContext.Provider value={store}>
        <main className={styles.main}>
          <InputWrapper />
          <List />
          <Footer />
        </main>
      </StoreContext.Provider>
    </>
  );
}

export default Home;
